# -*- coding: utf-8 -*-
"""Aula 6 - Código Morse

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T6NexAzQfIbl-uvw-6gTqhLj_6iDin7u

# Código Morse
"""

# Código Morse

# Este Código tem como entrada uma frase, que está criptografada, e como saída esta mesma frase descriptografada

# Primeiro é importante definir um dicionário
codigo_morse = {'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....','I': '..', 'J': '.---', 'K': '-.-',
                'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.','Q': '--.-', 'R': '.-.', 'S': '...', 'T': '-', 'U': '..-', 'V': '...-',
                'W': '.--', 'X': '-..-','Y': '-.--', 'Z': '--..', '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-','5': '.....', '6': '-....', '7': '--...', '8': '---..', '9': '----.'}

validar = True
while validar:
    frase_criptografada = input('''Digite a frase em código morse: 
    OBSERVAÇÃO: Separe as letras por 1 espaço, e as palavras por 2 espaços!!''')
    for letra in frase_criptografada:
        if letra not in ".- ":
            print('Essa frase possui caractéres inválidos. Digite novamente!')
            break
        else:
            validar = False

# Primeiro, vamos adicionar um espaço ao final da nossa frase criptografada
# Isso servirá para sabermos quando a nossa frase acabou
frase_criptografada = frase_criptografada + ' '
frase_descriptografada = '' # Essa variável vai guardar a nossa frase descriptografada
# Criaremos uma variável denominada "código", que armazenará os . e - de cada letra
codigo = '' # Ao final de cada letra, essa variável é "zerada"
for letra in frase_criptografada: # Vamos percorrer toda a nossa frase
# Sempre que tiver um espaço, sabemos que o código da letra acabou
    if letra != ' ': # Então, se não for espaço, ainda é o código da letra
        espaços = 0 # No início, a quantidade de espaços que temos é 0
        codigo = codigo + letra # Adicionamos a letra da frase na variável "código"
    else: # Se for espaço
        espaços = espaços + 1 # Então adicionamos 1 à nossa variável espaços
        if espaços == 2: # Se tivermos 2 espaços consecutivos, é um sinal de que temos uma separação de palavras
            # Então, adicionamos um espaço à nossa frase para separar as palavras
            frase_descriptografada = frase_descriptografada + ' '
        else: # Aqui que transformamos cada código em letra
            frase_descriptografada = frase_descriptografada + list(codigo_morse.keys())[list(codigo_morse.values()).index(codigo)]
            codigo = '' # Depois de descriptografar a letra, "zeramos" a nossa variável

print(f'A frase descriptografada é: "{frase_descriptografada}"')