# -*- coding: utf-8 -*-
"""Aula 4 - Cifra de César + Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xqu52s5fSNkRGE2sM8j3fpk7FcsjkCDL

# O que é Python?

Python é uma linguagem de programação. 

É uma linguagem que o computador entende e realiza as tarefas que a gente escrever.

Podemos escrever palavras, números, realizar operações, fazer comparações... 

Muitas coisas! Observe abaixo:
"""

#....

"""# Cifra de César

Você lembra da Cifra de César?

![](https://drive.google.com/uc?export=view&id=157FKQMvHGHQcjI9SkdyciksTCGRItv6Z)


Nessa aula iremos programar a Cifra de César usando o Python.
"""



texto = input('Digite a mensagem a ser encriptada ou decifrada: ')   # Solicitando o texto a ser encriptado ou decriptado:

chave = int(input('Entre com o valor da chave (deslocamento): '))    # Chave a ser utilizada

modo = input('Escolha E para encriptar ou D para decriptar o texto: ')   # Determinar modo de operação (E = encriptar; D = decriptar)

CARACTERES = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'    # Conjunto de caracteres válidos no algoritmo

convertido = ''   # Variável para armazenar o texto criptografado (ou decifrado)

texto = texto.upper()     # Converter todo o texto em maiúsculas:

for letra in texto:     # Código que será executdo em cada caractere do texto:
  if letra==" ":
      convertido=convertido+letra
  if letra in CARACTERES:
    num = CARACTERES.find(letra) # Obter o número criptografado ou decriptado do caractere
    if modo == 'E':                    # Obter o número do caractere
      num = num + chave
    if modo == 'D':
      num = num - chave
    if num >= len(CARACTERES):
      num = num - len(CARACTERES)
      convertido = convertido + CARACTERES[num]
    if num < 0:      
      num = num + len(CARACTERES)
      convertido = convertido + CARACTERES[num] 
    if num>0 and num<len(CARACTERES):                                
      convertido = convertido + CARACTERES[num]

if modo == 'E':
  print('O texto criptografado é ', convertido)
if modo == 'D':
  print('O texto decriptado é ', convertido)